### ISSUE TITLE
FAB shortly visible after app start if visibility=gone

### ISSUE THREAD

**Issue by Siegbaert** [TR4Android/AndroidSlidingUpPanel#17]
Given gollowing scenario:
- 1 Activity with SlidingUpPanel + FAB
- SlidingPanel default state = HIDDEN
- FAB visibility = gone

If you start the application you will see that the FAB is shortly visible (~ 0.5 seconds) and will then be gone.

Afterwards showing/hiding the FAB works perfectly.
I hope to have some time this week and try to look into it on my own.

**Comment by taltstidl** [comment]
@Siegbaert This is an issue with the AppCompat Support Design Library. See [Issue #182093](https://code.google.com/p/android/issues/detail?id=182093) of the Android Issue Tracker. The good news is, they seem to have a fix for it, the bad news is, they didn't release it yet. So you'll have to wait.
I'll be closing this issue. If the issue still persists after the official release with the fix, please reopen it. Thank you!

**Comment by Siegbaert** [comment]
Oh well... this didnt come up in my google search.
I wrote 2 different activities using a FAB. One with your changes to SlidingUpPanel lib and one without using the library. This bug didn't appear in the other activity so I thought it must be the lib causing the problem.
Sorry for bodering you and thank you very much!
