### ISSUE TITLE
Fab positioning

### ISSUE THREAD

**Issue by pengrad** [TR4Android/AndroidSlidingUpPanel#22]
Hi, thanks for nice library!
Can you please help me to build this layout.
In Expanded state fab should be here:
![screen shot 2016-01-27 at 12 39 33](https://cloud.githubusercontent.com/assets/2172170/12604983/0ec9c02c-c4f3-11e5-8021-aaa4103b8cbe.jpg)
And in the collapsed state here
![screen shot 2016-01-27 at 12 39 41](https://cloud.githubusercontent.com/assets/2172170/12604982/0e774202-c4f3-11e5-9055-3eb171ff00c3.jpg)

Thanks!

**Comment by taltstidl** [comment]
@pengrad As far as I know this should simply be copy and paste of the layout in the Readme, with the `umanoFabMode` set to `leave_behind`. Or did you encounter any issues doing that?

**Comment by pengrad** [comment]
Yes, it works perfect until I resize panel. Then I found wrong fab position in collapsed state.
Anyway thanks for quick response, I decided to self positioning with CoordinatorLayout.

**Comment by taltstidl** [comment]
@pengrad How did you resize panel? I'm still interested in resolving this.

**Comment by pengrad** [comment]
I have header (second child in SlidingPanel) as 

``` xml
<FrameLayout
            android:id="@+id/slide_header"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_weight="0.5"/>
```

and resize it with 

``` java
slideHeader.setLayoutParams(new SlidingUpPanelLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.MATCH_PARENT, 0.7f));
```

**Comment by taltstidl** [comment]
@pengrad Well, there's nothing I could do about that, you'd just have to call `requestLayout()` on the `FloatingActionButtonLayout` after this change.
