### ISSUE TITLE
My Floating Action Button became translucent

### ISSUE THREAD

**Issue by KirbyAbadilla** [TR4Android/AndroidSlidingUpPanel#9]
I have a sliding panel layout where I attach my fab, in my xml layout, inside of the sliding panel layout I put the fab as its third child. There's no error occurred but the fab button became translucent even if I tried to set its color. If I remove the fab button from the sliding layout as its child and put it outside where it will be the second child of the top most layout next to the sliding panel layout, the fab button will have a bug that results to irregularity or wrong positioning of the fab. most likely when you are trying to slide the sliding panel upwards or downwards.

**Comment by taltstidl** [comment]
@KirbyAbadilla Which fab mode are you using? Any chance you could post a screenshot so I can get a better idea?
Also note that positioning and animation of fab is only supported when it is used as the second child of the FloatingActionButtonLayout.

**Comment by KirbyAbadilla** [comment]
ooh I didn't notice that, i did not used FloatingActionButtonLayout. my bad, I thought that using com.sothree.slidinguppanel.SlidingUpPanelLayout will be okay. Sorry my bad, I am looking at the xml layout of the sample project. I will immediately respond after I change my layout into FloatingActionButtonLayout

**Comment by taltstidl** [comment]
@KirbyAbadilla My [Readme](https://github.com/TR4Android/AndroidSlidingUpPanel/blob/master/README.md) also has instructions on how to include this in your project. I actually planned to include this in the SlidingUpPanelLayout itself, but that caused the fab to disappear behind the panel.

**Comment by KirbyAbadilla** [comment]
Hi, thanks for your help. I am migrating to the new version of your androidslidinguppanel. I already fixed the bugs. the update is nice especially with the setPanelStatee(). I'm still exploring the new update :)

**Comment by taltstidl** [comment]
@KirbyAbadilla No problem. Glad that I could help. Some of the updates are from the original library though which is now version 3.0.0.

**Comment by KirbyAbadilla** [comment]
yes! its awesome!

**Comment by taltstidl** [comment]
@KirbyAbadilla Could you please close the issue as soon as you got everything to work and open a new more specific issue when you have problems? Thanks and have fun :wink:.

**Comment by taltstidl** [comment]
@KirbyAbadilla I'll close this issue now. If you still have problems feel free to reopen this issue or open a new more specific issue. Thanks.
